# Generated by Django 4.2.2 on 2023-12-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(max_length=4)),
                ('airport_name', models.CharField(max_length=255)),
                ('airport_country', models.CharField(max_length=2)),
                ('airport_latitude', models.FloatField(default=0)),
                ('airport_longitude', models.FloatField(default=0)),
                ('airport_elevation', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
